# Generated by Django 4.0.3 on 2022-04-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='board',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
