# Generated by Django 4.0.3 on 2022-04-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_session_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='board',
            field=models.FileField(default='images/sketch.png', upload_to='images'),
        ),
    ]
